# Generated by Django 2.0.1 on 2018-01-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('gender', models.CharField(blank=True, choices=[('m', 'meesssgu'), ('f', 'naissugu'), ('n', 'kesksugu')], max_length=1)),
                ('wordClass', models.CharField(blank=True, choices=[('v', 'tegus'), ('n', 'nimis'), ('a', 'omds'), ('d', 'määrs')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TranslatorsChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Term')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Term'),
        ),
    ]
