# Generated by Django 2.0.1 on 2018-01-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_auto_20180120_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Est',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField()),
                ('translation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(blank=True, max_length=100)),
                ('rootLang', models.CharField(blank=True, choices=[('pl', 'paali'), ('skr', 'sanskrit')], max_length=1)),
                ('rootDescription', models.CharField(blank=True, max_length=100)),
                ('expl', models.TextField(blank=True)),
                ('further', models.TextField(blank=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Term')),
            ],
        ),
        migrations.CreateModel(
            name='Pali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pali', models.CharField(max_length=100)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Term')),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Meaning'),
        ),
        migrations.AddField(
            model_name='est',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Meaning'),
        ),
        migrations.AddField(
            model_name='eng',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Meaning'),
        ),
    ]
