# Generated by Django 2.0.1 on 2018-01-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0005_auto_20180126_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='term',
            new_name='term_meaning',
        ),
    ]
