# Generated by Django 2.0.1 on 2018-01-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_lettertoadmin_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertoadmin',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
