# Generated by Django 2.0.1 on 2018-01-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='a@a.ee', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatorschat',
            name='email',
            field=models.EmailField(default='a@a.ee', max_length=254),
            preserve_default=False,
        ),
    ]
