# Generated by Django 2.0.1 on 2018-01-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0003_auto_20180121_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='rootLang',
            field=models.CharField(blank=True, choices=[('p', 'paali'), ('s', 'sanskrit')], max_length=1),
        ),
    ]
