# Generated by Django 2.0.1 on 2018-02-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0006_auto_20180126_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
