# Generated by Django 2.0.1 on 2018-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0008_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='eng',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
