# Generated by Django 2.0.1 on 2018-05-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0009_auto_20180514_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='def_in_PLS_dict',
            field=models.TextField(blank=True),
        ),
    ]
