# Generated by Django 2.0.1 on 2018-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='header',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
